### ISSUE TITLE
Error inserting CLOB value

### ISSUE THREAD

**Issue by ElenaLR** [taq/pdooci#24]
Hi, 
First of all, thank you for this library. 
I'm having problems while inserting rows with this library. Before migrating to it, the inserts worked fine but, after the migration, when I insert a row in a table that has a CLOB column, the value of this column is created always with the same value: `"-0,00000000000000000000000000000000E+125"`
During and after the execution, everything works ok, there are no exceptions or errors and the execution returns 'true'.

Have you had any problems like this before?
Would you mind telling me what I should look for in the code in order to fix it?

I have a table that has the following structure:

```
id INTEGER PK AUTO_INC
param_key VARCHAR(2048)
param_value CLOB
data_expires_at INTEGER'
```
This is the example code that I have been testing:

```
$conn = new PDO($dsn, $user, $pass);
$serObject = 'teststring';
$array     = array(
        "param_key"       => 'keystring',
        "param_value"     => 'test string that should be very long'
        "data_expires_at" => 1488800018,
);

$values      = array();
$name_params = array_keys($array);
for ($i = 0; $i < count($name_params); $i++) {
    $values[] = "?";
}

$query = "INSERT INTO " . $table . " (" . implode(",", $name_params) . ")";
$query .= " VALUES (" . implode(",", $values) . ")";

$sth2 = $conn->prepare($query);
$i    = 1;
foreach ($array as $name => $value) {
        if ($name == "param_value") { //This is the CLOB column
            $sth2->bindParam($i, $value, PDO::PARAM_STR, strlen($value)); 
                      //I fill in the third parameter with PARAM_STR because of the bug on the oficial library
                      // However, I have tried with PARAM_LOB and it keeps inserting the wrong value.
        } else {
            $sth2->bindParam($i, $value);
        }
        $i++;
}
$result = $sth2->execute();
[...]
```

Thank you very much, 

Best regards. 

Elena

**Comment by taq** [comment]
To be honest, I never used a CLOB with it. I'll take a look on it. ;-)

**Comment by ElenaLR** [comment]
Thank you very much! :D

**Comment by taq** [comment]
Your problem is not `PDOOCI`, but the way the PHP `foreach` works. If you check, probably all your columns will have the same value as the last `$value` variable value on the `foreach` loop. If you use code like 

```
$sth2->bindParam(1, $array["id"]);
$sth2->bindParam(2, $array["param_key"]);
$sth2->bindParam(3, $array["param_value"]);
$sth2->bindParam(4, $array["data_expires_at"]);
```

you can see that it works. Maybe is not the migration, but the way the language works, are you using a different PHP version or even a different server? 

If you take a look on the [PDO::bindParam method](http://php.net/manual/pt_BR/pdostatement.bindparam.php) (which `PDOOCI` must be *exactly compatible*), you can see that it takes the variable by reference:

```php
public bool PDOStatement::bindParam ( mixed $parameter , mixed &$variable [, int $data_type = PDO::PARAM_STR [, int $length [, mixed $driver_options ]]] )
```

Notice the `&$variable` there, is using its *reference*, not its *value*. Then, inside `PDOOCI`, to also be compatible, we call the [oci_bind_by_name method](http://php.net/manual/pt_BR/function.oci-bind-by-name.php), which **also** uses reference:

```
bool oci_bind_by_name ( resource $statement , string $bv_name , mixed &$variable [, int $maxlength = -1 [, int $type = SQLT_CHR ]] )
```

Then, you can check the behaviour of the PHP `foreach` method, and you'll see that when you use its value on the `bindParam` method, is always fixing it on the last value of `foreach`. 

If you change your loop to

```
foreach (array_keys($array) as $key) {
   $sth2->bindParam($i, $array[$key]);
   $i ++;
}
$result = $sth2->execute();
```
You'll see that you're protected from the tricky behaviour of PHP `foreach`. Even if you declared `$value` there as the result of the `$array[$key]` it won't work, you'll need to bind the `$array[$key]` thing.

**Comment by taq** [comment]
I think we can close this issue, as it is a PHP issue and not a PDOOCI issue, right?

**Comment by ElenaLR** [comment]
Thank you for your extremely quick response! I've reviewed my code and I've applied your suggestions and everything seems to work fine. I agree with you and I think that we can close this issue. 
Thank you very much.
Elena
